### ISSUE TITLE
npm start TypeError

### ISSUE THREAD

**Issue by Buskcoin** [lance-gg/lancegame#3]
I am unable to run `npm start` successfully. This is what I get after having already run `npm install`:
```
bash-3.2$ npm start

> lance-game@1.0.0 start /Users/name/Desktop/lancegame
> node main.js

PhysicsEngine:{
    "physicsEngine": {},
    "traceLevel": 1
}

/Users/name/Desktop/lancegame/node_modules/lance-gg/src/GameEngine.js:51
        this.physicsEngine = new PhysicsEngine();
                             ^

TypeError: PhysicsEngine is not a constructor
    at MyGameEngine.GameEngine (/Users/name/Desktop/lancegame/node_modules/lance-gg/src/GameEngine.js:51:30)
    at MyGameEngine (/Users/name/Desktop/lancegame/src/common/MyGameEngine.js:15:9)
    at Object.<anonymous> (/Users/name/Desktop/lancegame/main.js:24:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lance-game@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lance-game@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Administrator/.npm/_logs/2017-06-17T01_41_50_949Z-debug.log
bash-3.2$ node -v
v6.11.0
bash-3.2$ npm -v
5.0.3
bash-3.2$ 
```
What am I missing?

Thank you!

**Comment by Buskcoin** [comment]
Ok, I see now that I have to revert to a previous commit to run it successfully.

**Comment by OpherV** [comment]
@Buskcoin glad you got it sorted out :)
The develop branch of lance is where we do work for next versions, it's not guaranteed to be stable and backwards compatible with all the previous games, examples etc.

If you want the latest stable version make sure to use the master branch or the NPM version
