### ISSUE TITLE
`npm start` fails with import syntax error

### ISSUE THREAD

**Issue by copacetic** [lance-gg/lancegame#5]
I'm very excited to try lance! I just now tried to run `npm start` after downloading `lancegame` and having run `npm build` I hit the following error:
``` npm start                                

> lance-game@2.0.0 start /home/hayg/Documents/ungroup
> babel-node main.js --presets es2015

module.js:540
    throw err;
    ^

Error: Cannot find module 'lance/ServerEngine'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/hayg/Documents/ungroup/src/server/MyServerEngine.js:3:1)
    at Module._compile (module.js:643:30)
    at loader (/home/hayg/Documents/ungroup/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/hayg/Documents/ungroup/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

When I changed the imports to the syntax found in the tutorial ( http://docs.lance.gg/2.0.1/tutorial-MyFirstGame.html ), it started working. 

Thank you,
Hayg

**Comment by namel** [comment]
Hi, lancegame has just been fixed to match V2, and the [docs](http://docs.lance.gg/r2.0.5/tutorial-MyFirstGame.html) got a facelift as well to match the new version.

Please try again, and let me know if I can close this issue.

**Comment by gcphost** [comment]
Working here.
